name: pyway Testing OSX

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          brew install mariadb
          brew install postgresql
          
          # taken from https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
          brew update
          HOMEBREW_ACCEPT_EULA=Y brew install msodbcsql18 mssql-tools18
          
          python -m pip install --upgrade pip
          pip install flake8 pytest build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Build and install mysqld code
        run: |
          python -m build
          pip install dist/*.gz

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

      - name: Test with pytest
        run: |
          pytest -m "not integration_test" --skip-mssql-tests true
